.PHONY: clean All

All:
	@echo "----------Building project:[ cardgame_demo - Debug ]----------"
	@cd "cardgame_demo" && "$(MAKE)" -f  "cardgame_demo.mk"
clean:
	@echo "----------Cleaning project:[ cardgame_demo - Debug ]----------"
	@cd "cardgame_demo" && "$(MAKE)" -f  "cardgame_demo.mk" clean
