.PHONY: clean All

All:
	@echo "----------Building project:[ graph-quiz - Debug ]----------"
	@cd "graph-quiz" && "$(MAKE)" -f  "graph-quiz.mk"
clean:
	@echo "----------Cleaning project:[ graph-quiz - Debug ]----------"
	@cd "graph-quiz" && "$(MAKE)" -f  "graph-quiz.mk" clean
