.PHONY: clean All

All:
	@echo "----------Building project:[ matrix - Debug ]----------"
	@cd "matrix" && "$(MAKE)" -f  "matrix.mk"
clean:
	@echo "----------Cleaning project:[ matrix - Debug ]----------"
	@cd "matrix" && "$(MAKE)" -f  "matrix.mk" clean
