.PHONY: clean All

All:
	@echo "----------Building project:[ fibonacci30 - Debug ]----------"
	@cd "fibonacci30" && "$(MAKE)" -f  "fibonacci30.mk"
clean:
	@echo "----------Cleaning project:[ fibonacci30 - Debug ]----------"
	@cd "fibonacci30" && "$(MAKE)" -f  "fibonacci30.mk" clean
