.PHONY: clean All

All:
	@echo "----------Building project:[ float_to_binary - Debug ]----------"
	@cd "float_to_binary" && "$(MAKE)" -f  "float_to_binary.mk"
clean:
	@echo "----------Cleaning project:[ float_to_binary - Debug ]----------"
	@cd "float_to_binary" && "$(MAKE)" -f  "float_to_binary.mk" clean
