.PHONY: clean All

All:
	@echo "----------Building project:[ auto - Debug ]----------"
	@cd "auto" && "$(MAKE)" -f  "auto.mk"
clean:
	@echo "----------Cleaning project:[ auto - Debug ]----------"
	@cd "auto" && "$(MAKE)" -f  "auto.mk" clean
