.PHONY: clean All

All:
	@echo "----------Building project:[ discrete_event - Debug ]----------"
	@"$(MAKE)" -f  "discrete_event.mk"
clean:
	@echo "----------Cleaning project:[ discrete_event - Debug ]----------"
	@"$(MAKE)" -f  "discrete_event.mk" clean
