.PHONY: clean All

All:
	@echo "----------Building project:[ inh - Debug ]----------"
	@"$(MAKE)" -f  "inh.mk"
clean:
	@echo "----------Cleaning project:[ inh - Debug ]----------"
	@"$(MAKE)" -f  "inh.mk" clean
