.PHONY: clean All

All:
	@echo "----------Building project:[ demo1 - Debug ]----------"
	@cd "demo1" && "$(MAKE)" -f  "demo1.mk"
clean:
	@echo "----------Cleaning project:[ demo1 - Debug ]----------"
	@cd "demo1" && "$(MAKE)" -f  "demo1.mk" clean
